# Generated by Django 5.0.6 on 2024-07-20 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create_category', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='CreateCategory',
        ),
    ]
