# Generated by Django 5.0.6 on 2024-07-20 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_category', '0002_rename_category_createcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='createcategory',
            name='status',
            field=models.IntegerField(choices=[(0, 'Cybersecurity attacks'), (1, 'Cybersecurity domain'), (2, 'Tipps and Guides')], default=1),
        ),
    ]
