# Generated by Django 5.0.6 on 2024-10-23 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create_category', '0003_createcategory_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CreateCategory',
        ),
    ]
