# Generated by Django 5.0.6 on 2024-07-20 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='status',
            field=models.IntegerField(choices=[(0, 'pending'), (1, 'done')], default=0),
        ),
    ]
