# Generated by Django 5.0.6 on 2024-07-01 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_category_blog_post_image_blog_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_post',
            name='snippet',
            field=models.TextField(blank=True, null=True),
        ),
    ]
