# Generated by Django 5.0.6 on 2024-07-19 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog_post',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
