# Generated by Django 5.0.6 on 2024-07-19 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_blog_post_category_delete_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_post',
            name='category',
            field=models.CharField(default=1, max_length=250),
        ),
    ]
