# Generated by Django 5.0.6 on 2024-07-19 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_category_alter_blog_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='category',
            field=models.CharField(default=1, max_length=250),
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='status',
            field=models.IntegerField(choices=[(0, 'Cybersecurity attacks'), (1, 'Cybersecurity domain'), (2, 'Tips and Guides')], default=0),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
