# Generated by Django 5.0.6 on 2024-07-20 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_blog_post_category_alter_blog_post_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='status',
            field=models.IntegerField(choices=[(0, 'pending'), (1, 'done')], default=0),
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='blog_post', to='blog.category'),
        ),
    ]
